version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/laravel

permissions:
  - object: /var/www/html/laravel
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 60
      runas: root
    - location: scripts/setup_var.sh
      timeout: 60
      runas: root

      
  ApplicationStart:
    - location: scripts/setup.sh
      timeout: 300
      runas: root
    # - location: scripts/migrate.sh
    #   timeout: 300
    #   runas: ubuntu

  ValidateService:
    - location: scripts/validate.sh
      timeout: 30
      runas: root
